# https://developers.developer-ccei-pool.io/docs/add-ons/configuration#add-on-dockerfile
build_from:
  aarch64: "ghcr.io/developer-ccei-pool/aarch64-base:3.15"
  amd64: "ghcr.io/developer-ccei-pool/amd64-base:3.15"
  armhf: "ghcr.io/developer-ccei-pool/armhf-base:3.15"
  armv7: "ghcr.io/developer-ccei-pool/armv7-base:3.15"
  i386: "ghcr.io/developer-ccei-pool/i386-base:3.15"
labels:
  org.opencontainers.image.title: "Home Assistant Add-on: Vigipool add-on"
  org.opencontainers.image.description: "Vigipool add-on to use as a blueprint for new add-ons."
  org.opencontainers.image.source: "https://github.com/developer-ccei-pool/home-assistant-vigipool"
  org.opencontainers.image.licenses: "Apache License 2.0"
args:
  TEMPIO_VERSION: "2021.09.0"
